package com.staysure.operations.enums;

public enum NotificationType {
    COMPLAINT_CREATED,
    COMPLAINT_ACKNOWLEDGED,
    COMPLAINT_IN_PROGRESS,
    COMPLAINT_RESOLVED,
    COMPLAINT_COMMENT_ADDED,
    COMPLAINT_REOPENED,
    COMPLAINT_CANCELLED,
    NOTICE_PUBLISHED,
    VISITOR_REQUESTED,
    VISITOR_APPROVED,
    VISITOR_REJECTED,
    RENT_INVOICE_GENERATED,
    RENT_PAYMENT_RECORDED,
    BOOKING_APPROVED,
    BOOKING_REJECTED,
    BOOKING_CONFIRMED,
    KYC_REJECTED
}
